### ISSUE TITLE
Gradlew: Permission denied

### ISSUE THREAD

**Issue by WtfJoke** [actions/starter-workflows#171] opened 2019-10-20 21:26 UTC
Hi there

I setup a new gradle workflow and have following error in my log:

```
Run ./gradlew build
/home/runner/work/_temp/46af0a17-aff6-47ea-ab02-304aec292273.sh: line 1: ./gradlew: Permission denied
```

I used following config (same as [gradle.yml](https://github.com/actions/starter-workflows/blob/master/ci/gradle.yml)):
```yml
name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
```

I fixed it by adding an additional step:
```yml
    - name: Make gradlew executable
      run: chmod +x ./gradlew
```

Is this a mistake? Or some issue on my end?
If you want I can make a PR for that.

**Comment by bryanmacfarlane** [comment] 2019-10-21 03:35
The gradlew file is checked into your repo.  It should have executable bit set.  Do a chmod +ux on the file and then push it - git will retain the executable bit.

I don't believe it's an actions thing (or should take a PR) because outside of actions, if a dev cloned your repo, he would expect to be able to run ./gradlew and it would fail (without actions in the picture).

Make sense?

**Comment by ethomson** [comment] 2019-10-21 10:11
As @bryanmacfarlane mentioned, the underlying problem is that the file is not executable, which you'll need to change in your repository.  If you're on Windows, that may be why the file did not get added as executable in your repository.  On Windows, you can run:

    git update-index --chmod=+x gradlew

Then commit and push this change.

**Comment by ethomson** [comment] 2019-10-21 10:13
Since this is a general issue with the way that Unix execute permissions work, and not something that GitHub Actions can itself change, I'm going to close this issue.

**Closed by ethomson** 2019-10-21 10:13 UTC

**Comment by WtfJoke** [comment] 2019-10-21 10:51
Thanks for your answers :)

**Comment by jdruedaq** [comment] 2019-11-18 14:23
> Hi there
> 
> I setup a new gradle workflow and have following error in my log:
> 
> ```
> Run ./gradlew build
> /home/runner/work/_temp/46af0a17-aff6-47ea-ab02-304aec292273.sh: line 1: ./gradlew: Permission denied
> ```
> 
> I used following config (same as [gradle.yml](https://github.com/actions/starter-workflows/blob/master/ci/gradle.yml)):
> 
> ```yaml
> name: Java CI
> 
> on: [push]
> 
> jobs:
>   build:
> 
>     runs-on: ubuntu-latest
> 
>     steps:
>     - uses: actions/checkout@v1
>     - name: Set up JDK 1.8
>       uses: actions/setup-java@v1
>       with:
>         java-version: 1.8
>     - name: Build with Gradle
>       run: ./gradlew build
> ```
> 
> I fixed it by adding an additional step:
> 
> ```yaml
>     - name: Make gradlew executable
>       run: chmod +x ./gradlew
> ```
> 
> Is this a mistake? Or some issue on my end?
> If you want I can make a PR for that.

it's works 💃

**Comment by bryanmacfarlane** [comment] 2019-11-18 19:16
You need to make the file executable locally and push the change (git persists the executable bit).  That's needed outside of the workflow in the event another developer clones your repo and wants to run it.

**Comment by priyakdey** [comment] 2022-09-30 16:40
> As @bryanmacfarlane mentioned, the underlying problem is that the file is not executable, which you'll need to change in your repository. If you're on Windows, that may be why the file did not get added as executable in your repository. On Windows, you can run:
> 
> ```
> git update-index --chmod=+x gradlew
> ```
> 
> Then commit and push this change.

I use to do this, and then it came across my mind, is it really safe to give execute permission for all users for a file kept on a remote server? I do understand that GitHub being **GitHub** has all kinds of security, but I still feel that adding a step to run `chmod +x gradlew` or running `chmod +x gradlew && ./gradlew {goals}` is a safer option.

Though [this document](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions) does not comment on how the servers are running, my assumption would be the target hosts are running the jobs inside a container or the running machine is just an lxc (I may be wrong here and tend to research on how it is being done). So giving an execute permission just for the scope of the run of the script is better than giving it execute permission on the storage.

**Comment by Gameking1happy** [comment] 2025-10-24 15:24
google leads to this, and tried "git update-index --chmod=+x gradlew", thing is nothing changes, IDK what the problem is, is there anything else to try?
