### ISSUE TITLE
Build Windows Application

### ISSUE THREAD

**Issue by jingsong-liu** [actions/starter-workflows#377] opened 2020-03-01 06:20 UTC
https://github.com/actions/starter-workflows/blob/223033b681b9924324537ee1cb2f41f383f0ef21/ci/dotnet-core.yml#L12

What shuould I use for key `run on` when I want to build Windows Applications
My project action is building WPF app based on dotnet core 3.1

**Comment by ethomson** [comment] 2020-03-03 11:31
Hi @jingsong-liu, you should use `runs-on: windows-latest`.

I'm going to close this issue as it's not a bug in the starter workflows.  If you have other questions, I'd suggest using [github.community](https://github.community), where you will likely get a timelier response.  Thanks!

**Closed by ethomson** 2020-03-03 11:31 UTC

**Comment by jingsong-liu** [comment] 2020-03-03 11:52
thanks so much
