### ISSUE TITLE
Need template for modern C++ w/ cmake

### ISSUE THREAD

**Issue by dvtate** [actions/starter-workflows#586] opened 2020-07-11 17:19 UTC
Hi, my C++ projects use language features that have been added within the past 3 years and Cmake

I read that the VM has a fairly recent version of GCC installed (9.3), but it doesn't appear to be used by default. How do I switch to a more modern compiler? bonus points if same approach also works for windows + macos + clang

**I feel like using modern C++ language features and Cmake are both pretty common so I think that having a template for this would be pretty useful**

**Comment by dvtate** [comment] 2020-07-19 04:16
You seriously have 6 different examples for javascript, but only a single example that's targeting C/C++ and only uses gcc 4.9, which was released in 2014 btw

**Comment by hiloboi** [comment] 2020-08-02 03:59
``[]() 
Thank you for completing the OAuth flow.KWSdYIUsing OAuth 2.0 for Web Server Applications | Google Identity ..._yqH6YFJoLvFmyVw
Click here to verify that your Proxy URL is set up correctly.

**Comment by Geod24** [comment] 2020-08-04 11:08
@dvtate : If you want a workflow that handles a lot of C++ compilers, on all three platforms, this is what we are using: https://github.com/dlang/dmd/blob/86c4cd1819fd26a822e0b1daf09f460dd5a3043e/.github/workflows/runnable_cxx.yml

It's a beast, but it works, and it's pretty easy to remove some of the compilers you don't want.

**Comment by dvtate** [comment] 2020-08-04 21:42
@Geod24 thanks!

**Comment by leftour** [comment] 2020-10-30 19:29
C++ يحتل لحين الصدارة رغم أنه يحتاج بعد التطور لم قيل هذه المهام

**Comment by dvtate** [comment] 2021-01-29 19:06
bump

**Comment by SonjayaJetBrain** [comment] 2021-04-14 17:02
closing upstream with trv >wow

**Comment by SonjayaJetBrain** [comment] 2021-04-14 17:02
almost ready >wow

**Comment by dvtate** [comment] 2021-04-14 17:14
?

**Comment by dvtate** [comment] 2021-04-14 17:15
@SonjayaJetBrain ?

**Comment by dvtate** [comment] 2021-04-28 05:00
for those in the future I've been able to specify the gcc/g++ version 9 which supports C++20 but I still feel like if there's 200000 javascript/typescript/java templates that C++ deserves similar treatment. And it would make sense to at least have a cmake/c++20 template
https://github.com/dvtate/SCL/blob/master/.github/workflows/c-cpp.yml

**Comment by Dnuts23** [comment] 2021-06-29 03:51
> @
Duplicate of #: If you want a workflow that handles a lot of C++ compilers, on all three platforms, this is what we are using: https://github.com/dlang/dmd/blob/86c4cd1819fd26a822e0b1daf09f460dd5a3043e/.github/workflows/runnable_cxx.yml
> 
> It's a beast, but it works, and it's pretty easy to remove some of the compilers you don't want.

**Comment by Geod24** [comment] 2021-09-27 05:02
Issues don't magically solve themselves because people don't comment on it. So let me comment on it.

**Closed** 2022-01-04 04:30 UTC
Labels: no-issue-activity

**Comment by dvtate** [comment] 2022-01-05 22:01
:/
