### ISSUE TITLE
Pause on accepting on new community starter workflows

### ISSUE THREAD

**Issue by andymckay** [actions/starter-workflows#631] opened 2020-08-21 01:08 UTC
👋🏾 Hi there

As you can probably tell, we haven't been very good at merging in new starter workflows in to this repository. First off I'd like to apologise to everyone who has submitted a new starter workflow. Thank you for submitting them and our apologies for not accepting them sooner.

We'd love to have more starter workflows appear on the Actions tab, but at this time the page just doesn't work well with lots of new starter workflows. Having a team try to process and understand the starter workflows hasn't worked too well.  

Perhaps we need to make starter workflows more like the Marketplace, so a community can publish and update workflows without needing approval. That's something we are exploring for the future.

At this time I think its unfair to starter workflow authors to submit them and then have nothing happen with them for a long period of time. Rather than create unfair expectations we are temporarily going to **stop accepting new** starter workflows. We **will try to merge all the ones already submitted**, see below 👇🏾 for that list.

Sorry about that, but hope this is temporary and we'll figure something else out that's better for the future.

This are the starter workflows we are going to try and merge in:

- [x] https://github.com/actions/starter-workflows/pull/605 or https://github.com/actions/starter-workflows/pull/580 Nix - changes requested.
- [x] https://github.com/actions/starter-workflows/pull/604 Deno - changes requested.
- [x] https://github.com/actions/starter-workflows/pull/591 Phoenix - changes requested.
- [x] https://github.com/actions/starter-workflows/pull/587 Ionic - changes requested.
- [x] https://github.com/actions/starter-workflows/pull/576 or https://github.com/actions/starter-workflows/pull/489 Open shift - changes requested.
- [x] https://github.com/actions/starter-workflows/pull/546 or https://github.com/actions/starter-workflows/pull/74 D Lang
- [x] https://github.com/actions/starter-workflows/pull/526 Symfony - changes requested.
- [x] https://github.com/actions/starter-workflows/pull/493 Ada - changes requested.
- [x] https://github.com/actions/starter-workflows/pull/460 iOS - changes requested.
- [x] https://github.com/actions/starter-workflows/pull/329 Hakyll - 😢 
- [x] https://github.com/actions/starter-workflows/pull/321 ASP.NET core deployment to Azure - changes requested.
- [x] https://github.com/actions/starter-workflows/pull/311 Cypress - changes requested.
- [x] https://github.com/actions/starter-workflows/pull/298 Pylint
- [x] https://github.com/actions/starter-workflows/pull/268 Sharepoint Framework - changes requested.
- [x] https://github.com/actions/starter-workflows/pull/227 Platform IO - 😢
- [x] https://github.com/actions/starter-workflows/pull/201 Rushjs - changes requested.
- [x] https://github.com/actions/starter-workflows/pull/197 Python using Anaconda
- [x] https://github.com/actions/starter-workflows/pull/166 R
- [x] https://github.com/actions/starter-workflows/pull/118 XCode CI - I think this will be replaced with #460 ☝🏾 
- [x] https://github.com/actions/starter-workflows/pull/47 cmake - changes requested.

**Comment by HonkingGoose** [comment] 2020-08-30 10:37
@andymckay Can you maybe rename the issue to something like "Temporary stop on accepting new starter workflows" and [pin this issue](https://docs.github.com/en/github/managing-your-work-on-github/pinning-an-issue-to-your-repository) to the top of the issue screen? I think this would increase visibility.

**Comment by andymckay** [comment] 2020-08-31 19:01
Good idea, pinned 🙇🏾

**Comment by Emiliano978** [comment] 2020-10-17 21:11
[https://instagram.com/brunadiano68?igshid=1gcclzx7k1zea](ci/dotnet-core.yml) @
Duplicate of

**Comment by FREELANCEGITIT** [comment] 2021-02-22 03:03
Great

**Comment by nzm47** [comment] 2021-03-19 11:43
name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by Denda23** [comment] 2021-04-18 10:09
steps:
  # Checks out a copy of your repository on the ubuntu-latest machine
  - name: Checkout code
    uses: actions/checkout@v2

  # Runs the Super-Linter action
  - name: Run Super-Linter
    uses: github/Denda23
    env:
      DEFAULT_BRANCH: main
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by Denda23** [comment] 2021-04-18 12:55
name: Run Super-Linter
uses: github/Denda23
env:
DEFAULT_BRANCH: main
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by Fietzi** [comment] 2021-09-21 22:16
steps:
  # Checks out a copy of your repository on the ubuntu-latest machine
  - name: Checkout code
    uses: actions/checkout@v2

  # Runs the Super-Linter action
  - name: Run Super-Linter
    uses: github/super-linter@v3
    env:
      DEFAULT_BRANCH: main
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by Yanz-dotcom** [comment] 2021-11-10 17:57
gh pr checkout 1212
[Uploading starter-workflows-ed5cb0096e70c082ac4b02ed25d3fc8b24a41525.zip…]()

**Comment by m-github-org** [comment] 2021-11-14 23:11
> 👋🏾 سلام
> 
> همانطور که احتمالاً می توانید بگویید، ما در ادغام جریان های کاری شروع کننده جدید در این مخزن خیلی خوب عمل نکرده ایم. ابتدا می‌خواهم از همه کسانی که یک گردش کار شروع جدید ارسال کرده‌اند عذرخواهی کنم. از ارسال آنها متشکریم و از اینکه زودتر قبول نشدیم عذرخواهی می کنیم.
> 
> ما دوست داریم که گردش‌های کاری آغازگر بیشتری در تب Actions ظاهر شود، اما در حال حاضر صفحه با تعداد زیادی گردش کار شروع کننده جدید به خوبی کار نمی‌کند. تلاش تیمی برای پردازش و درک جریان های کاری آغازگر خیلی خوب کار نکرده است.
> 
> شاید ما نیاز داشته باشیم که گردش‌های کاری آغازین را بیشتر شبیه به Marketplace کنیم تا یک جامعه بتواند گردش‌های کاری را بدون نیاز به تأیید منتشر و به‌روزرسانی کند. این چیزی است که ما در حال بررسی برای آینده هستیم.
> 
> در حال حاضر، من فکر می کنم ناعادلانه است که نویسندگان گردش کار شروع به ارسال آنها کنند و بعد برای مدت طولانی هیچ اتفاقی برای آنها نیفتد. به‌جای ایجاد انتظارات ناعادلانه، ما به‌طور موقت **از پذیرش** جریان‌های کاری آغازگر **جدید** خودداری می‌کنیم. ما **سعی خواهیم کرد همه مواردی که قبلا ارسال شده را با هم ادغام کنیم** ، برای آن لیست به زیر مراجعه کنید 👇🏾.
> 
> از این بابت متاسفم، اما امیدواریم این موقتی باشد و ما چیز دیگری را که برای آینده بهتر است کشف کنیم.
> 
> این جریان‌های کاری آغازینی هستند که می‌خواهیم امتحان کنیم و در آنها ادغام کنیم:
> 
> * [x]  [اضافه کردن nix starter  #605](https://github.com/actions/starter-workflows/pull/605) یا[ nix: افزودن Nix action  #580](https://github.com/actions/starter-workflows/pull/580) Nix - تغییرات درخواست شده است.
> * [x]  [Deno  #604](https://github.com/actions/starter-workflows/pull/604) Deno را اضافه کنید - تغییرات درخواست شده است.
> * [x]  [Add Phoenix starter workflow #591](https://github.com/actions/starter-workflows/pull/591) Phoenix - changes requested.
> * [x]  [Hammad tariq patch 1 #587](https://github.com/actions/starter-workflows/pull/587) Ionic - changes requested.
> * [x]  [ci: add openshift action #576](https://github.com/actions/starter-workflows/pull/576) or [IBM OpenShift example Action #489](https://github.com/actions/starter-workflows/pull/489) Open shift - changes requested.
> * [x]  [Add D workflow #546](https://github.com/actions/starter-workflows/pull/546) or [Add DLang workflow #74](https://github.com/actions/starter-workflows/pull/74) D Lang
> * [x]  [Add Symfony template #526](https://github.com/actions/starter-workflows/pull/526) Symfony - changes requested.
> * [x]  [Ada starter workflow, icon and properties #493](https://github.com/actions/starter-workflows/pull/493) Ada - changes requested.
> * [x]  [Add iOS Starter Workflow #460](https://github.com/actions/starter-workflows/pull/460) iOS - changes requested.
> * [x]  [Add Hakyll starter workflow #329](https://github.com/actions/starter-workflows/pull/329) Hakyll - 😢
> * [x]  [Adds starter workflow for ASP.NET Core deployment to Azure #321](https://github.com/actions/starter-workflows/pull/321) ASP.NET core deployment to Azure - changes requested.
> * [x]  [add Cypress starter workflow #311](https://github.com/actions/starter-workflows/pull/311) Cypress - changes requested.
> * [x]  [Pylint #298](https://github.com/actions/starter-workflows/pull/298) Pylint
> * [x]  [Added files for SPFx starter workflow #268](https://github.com/actions/starter-workflows/pull/268) Sharepoint Framework - changes requested.
> * [x]  [Add PlatformIO workflow #227](https://github.com/actions/starter-workflows/pull/227) Platform IO - 😢
> * [x]  [Create rushjs workflow #201](https://github.com/actions/starter-workflows/pull/201) Rushjs - changes requested.
> * [x]  [Python package unit testing using Anaconda #197](https://github.com/actions/starter-workflows/pull/197) Python using Anaconda
> * [x]  [Add R starter workflow #166](https://github.com/actions/starter-workflows/pull/166) R
> * [x]  [Xcode CI #118](https://github.com/actions/starter-workflows/pull/118) XCode CI - I think this will be replaced with [Add iOS Starter Workflow #460](https://github.com/actions/starter-workflows/pull/460) ☝🏾
> * [x]  [Add a starter cmake workflow #47](https://github.com/actions/starter-workflows/pull/47) cmake - changes requested.

#1247 #1239 #1244 #1239 #1239

**Comment by Anonymousx-legon** [comment] 2021-11-17 10:17
Hi. I am really sorry about my repository there. And I would like to thank you for your contribution on saying so. Also, that was a long time ago, before the API and all the sources for the keys were working well. I deeply apologize for that. I was away for so long also and that is why I took long to come back in and see all the tasks I have :) 

Thank you again brother.

**Comment by Chrobob2021** [comment] 2021-11-22 08:08
> 👋🏾 Hi there
> 
> As you can probably tell, we haven't been very good at merging in new starter workflows in to this repository. First off I'd like to apologise to everyone who has submitted a new starter workflow. Thank you for submitting them and our apologies for not accepting them sooner.
> 
> We'd love to have more starter workflows appear on the Actions tab, but at this time the page just doesn't work well with lots of new starter workflows. Having a team try to process and understand the starter workflows hasn't worked too well.
> 
> Perhaps we need to make starter workflows more like the Marketplace, so a community can publish and update workflows without needing approval. That's something we are exploring for the future.
> 
> At this time I think its unfair to starter workflow authors to submit them and then have nothing happen with them for a long period of time. Rather than create unfair expectations we are temporarily going to **stop accepting new** starter workflows. We **will try to merge all the ones already submitted**, see below 👇🏾 for that list.
> 
> Sorry about that, but hope this is temporary and we'll figure something else out that's better for the future.
> 
> This are the starter workflows we are going to try and merge in:
> 
> * [x]  [Add nix starter #605](https://github.com/actions/starter-workflows/pull/605) or [nix: add Nix action #580](https://github.com/actions/starter-workflows/pull/580) Nix - changes requested.
> * [x]  [Add Deno #604](https://github.com/actions/starter-workflows/pull/604) Deno - changes requested.
> * [x]  [Add Phoenix starter workflow #591](https://github.com/actions/starter-workflows/pull/591) Phoenix - changes requested.
> * [x]  [Hammad tariq patch 1 #587](https://github.com/actions/starter-workflows/pull/587) Ionic - changes requested.
> * [x]  [ci: add openshift action #576](https://github.com/actions/starter-workflows/pull/576) or [IBM OpenShift example Action #489](https://github.com/actions/starter-workflows/pull/489) Open shift - changes requested.
> * [x]  [Add D workflow #546](https://github.com/actions/starter-workflows/pull/546) or [Add DLang workflow #74](https://github.com/actions/starter-workflows/pull/74) D Lang
> * [x]  [Add Symfony template #526](https://github.com/actions/starter-workflows/pull/526) Symfony - changes requested.
> * [x]  [Ada starter workflow, icon and properties #493](https://github.com/actions/starter-workflows/pull/493) Ada - changes requested.
> * [x]  [Add iOS Starter Workflow #460](https://github.com/actions/starter-workflows/pull/460) iOS - changes requested.
> * [x]  [Add Hakyll starter workflow #329](https://github.com/actions/starter-workflows/pull/329) Hakyll - 😢
> * [x]  [Adds starter workflow for ASP.NET Core deployment to Azure #321](https://github.com/actions/starter-workflows/pull/321) ASP.NET core deployment to Azure - changes requested.
> * [x]  [add Cypress starter workflow #311](https://github.com/actions/starter-workflows/pull/311) Cypress - changes requested.
> * [x]  [Pylint #298](https://github.com/actions/starter-workflows/pull/298) Pylint
> * [x]  [Added files for SPFx starter workflow #268](https://github.com/actions/starter-workflows/pull/268) Sharepoint Framework - changes requested.
> * [x]  [Add PlatformIO workflow #227](https://github.com/actions/starter-workflows/pull/227) Platform IO - 😢
> * [x]  [Create rushjs workflow #201](https://github.com/actions/starter-workflows/pull/201) Rushjs - changes requested.
> * [x]  [Python package unit testing using Anaconda #197](https://github.com/actions/starter-workflows/pull/197) Python using Anaconda
> * [x]  [Add R starter workflow #166](https://github.com/actions/starter-workflows/pull/166) R
> * [x]  [Xcode CI #118](https://github.com/actions/starter-workflows/pull/118) XCode CI - I think this will be replaced with [Add iOS Starter Workflow #460](https://github.com/actions/starter-workflows/pull/460) ☝🏾
> * [x]  [Add a starter cmake workflow #47](https://github.com/actions/starter-workflows/pull/47) cmake - changes requested.

[BOB.Myanmar ](url)

**Comment by bishal-pdMSFT** [comment] 2022-03-25 10:30
Not stale.

**Comment by mvecha** [comment] 2022-04-13 19:05
Hi all,

Can someone please look into the required approvals needed to merge : https://github.com/actions/starter-workflows/pull/1512. It has been quite many days this is pending. 
Thanks in advance.

**Comment by Newman1515** [comment] 2022-05-04 22:56
# Contributor Covenant Code of Conduct

## Our Pledge

In the interest of fostering an open and welcoming environment, we as
contributors and maintainers pledge to make participation in our project and
our community a harassment-free experience for everyone, regardless of age, body
size, disability, ethnicity, sex characteristics, gender identity and expression,
level of experience, education, socio-economic status, nationality, personal
appearance, race, religion, or sexual identity and orientation.

## Our Standards

Examples of behavior that contributes to creating a positive environment
include:

* Using welcoming and inclusive language
* Being respectful of differing viewpoints and experiences
* Gracefully accepting constructive criticism
* Focusing on what is best for the community
* Showing empathy towards other community members

Examples of unacceptable behavior by participants include:

* The use of sexualized language or imagery and unwelcome sexual attention or
  advances
* Trolling, insulting/derogatory comments, and personal or political attacks
* Public or private harassment
* Publishing others' private information, such as a physical or electronic
  address, without explicit permission
* Other conduct which could reasonably be considered inappropriate in a
  professional setting

## Our Responsibilities

Project maintainers are responsible for clarifying the standards of acceptable
behavior and are expected to take appropriate and fair corrective action in
response to any instances of unacceptable behavior.

Project maintainers have the right and responsibility to remove, edit, or
reject comments, commits, code, wiki edits, issues, and other contributions
that are not aligned to this Code of Conduct, or to ban temporarily or
permanently any contributor for other behaviors that they deem inappropriate,
threatening, offensive, or harmful.

## Scope

This Code of Conduct applies within all project spaces, and it also applies when
an individual is representing the project or its community in public spaces.
Examples of representing a project or community include using an official
project e-mail address, posting via an official social media account, or acting
as an appointed representative at an online or offline event. Representation of
a project may be further defined and clarified by project maintainers.

## Enforcement

Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting the project team at opensource@github.com. All
complaints will be reviewed and investigated and will result in a response that
is deemed necessary and appropriate to the circumstances. The project team is
obligated to maintain confidentiality with regard to the reporter of an incident.
Further details of specific enforcement policies may be posted separately.

Project maintainers who do not follow or enforce the Code of Conduct in good
faith may face temporary or permanent repercussions as determined by other
members of the project's leadership.

## Attribution

This Code of Conduct is adapted from the [Contributor Covenant][homepage], version 1.4,
available at https://www.contributor-covenant.org/version/1/4/code-of-conduct.html

[homepage]: https://www.contributor-covenant.org

For answers to common questions about this code of conduct, see
https://www.contributor-covenant.org/faq

**Comment by Andre601** [comment] 2022-07-27 23:16
Can we still suggest new future starter workflows through issues? Or is that also on hold right now?

**Comment by cryptoquick** [comment] 2023-01-07 22:21
Not stale.

**Comment by studioromeo** [comment] 2023-01-19 21:39
Hey! 👋 

I know you're not accepting community workflows right now butI wanted to ask if you are interested in adding a starter workflow for the [eleventy static site generator](https://www.11ty.dev/). 

If so I can submit a PR.

Diff is here https://github.com/actions/starter-workflows/compare/main...studioromeo:starter-workflows:pages/eleventy?expand=1

Workflow test repo: https://github.com/studioromeo/eleventy-action

Thanks!

**Closed** 2023-04-28 04:26 UTC
Labels: no-issue-activity

**Comment by AMDphreak** [comment] 2026-03-08 20:35
This causes a problem though. Now, new and better alternatives will never gain traction as they are not officially endorsed in GitHub's setup process. You should make the Marketplace more prominent. The way to access Marketplace is hidden behind the "set up a workflow yourself" link. This is misleading and prevents users from even discovering the marketplace. If a user wanted to set it up themselves, they wouldn't be looking for a template. Your semantics and UI's organization here are a problem. Community starter workflows are nothing more than templates, just like the ones on the marketplace. You need to expose them IN THE SAME dialog so they are at the same valence level.

Notice that your wording on the site is "Choose a workflow". To the user, this means, "find a template, regardless of where it came from". There should be no separation between the marketplace and these more "curated" templates. There needs to be an opportunity for communities to cross the boundary between "unofficial" and "official" without phoning up GitHub corporate.

<img width="1468" height="745" alt="Image" src="https://github.com/user-attachments/assets/aac58b9a-d21d-4639-a080-7e3430e543d0" />


Fixing this kind of inconsistent accessibility is what we have all these AI's for. Let's get this fixed within a month please.

**Comment by AMDphreak** [comment] 2026-03-08 20:49
Diagrams for previous comment:

# GitHub Actions workflow chooser: hierarchy inconsistency

User intent: **"Find a template"** (any source).  
Current UI: two paths with different visibility and misleading wording.

## Current state (problem)

```mermaid
flowchart TB
  subgraph intent["User intent: Choose a workflow (find a template)"]
    A["Choose a workflow"]
  end

  A --> B["Starter workflows (curated)"]
  A --> C["Set up a workflow yourself"]

  B --> B1["Templates shown in same dialog"]
  C --> C1["Link leads to Marketplace"]

  subgraph prominence["Prominence / valence"]
    B1 --- high["High — visible by default"]
    C1 --- low["Low — hidden; label suggests manual setup, not more templates"]
  end

  style B fill:#e8f5e9
  style C fill:#ffebee
  style C1 fill:#ffcdd2
  style low fill:#ffcdd2
```

**Why it's inconsistent:**

- Same user goal ("pick a template"), but two different valence levels.
- "Set up a workflow yourself" sounds like *no* template — so users don't discover the Marketplace.
- Community/Marketplace templates are de facto "second class" despite being the same kind of content (templates).

## Desired state (same valence)

```mermaid
flowchart LR
  subgraph desired["Single dialog, equal valence"]
    A["Choose a workflow"]
    A --> B["Starter workflows"]
    A --> C["Marketplace / community workflows"]
  end

  B & C --- same["Same dialog, same prominence — user sees all templates in one place"]
  style B fill:#e8f5e9
  style C fill:#e8f5e9
```

**Fix:** Expose Marketplace in the *same* dialog as starter workflows so both are "choose a template" options at the same level. No separate path that implies "I'll do it myself."

**Comment by Destop-Trang1801** [comment] 2026-03-09 04:35
Vào Thứ 2, 9 thg 3, 2026 lúc 03:50 Ryan Johnson ***@***.***>
đã viết:

**Comment by AMDphreak** [comment] 2026-03-09 06:42
> Vào Thứ 2, 9 thg 3, 2026 lúc 03:50 Ryan Johnson ***@***.***>
> đã viết:
> […](#)

Your reply contained no message.
