### ISSUE TITLE
Pages jekyll publishing workflow results in incorrect `baseurl`

### ISSUE THREAD

**Issue by bertptrs** [actions/starter-workflows#1673] opened 2022-08-10 21:24 UTC
In the starter template for publishing a jekyll-based site to Github pages using the new Actions infrastructure, it shows how you can autodetect the correct publishing URL:

https://github.com/actions/starter-workflows/blob/1c7042ea97a8e1a5d5d3bc0d75ab33984912f3d4/pages/jekyll.yml#L36-L39

As the comment suggests, this results in just "`/`" for the main site published to a domain (e.g. `example.com`) and to something like `/subfolder/` for subprojects.

This is not what Jekyll expects; in fact the default configuration has `baseurl` be the empty string: https://jekyllrb.com/docs/configuration/default/

If you have a site that uses `baseurl` as a prefix to support separate deployments, the URLs generated will now start with two leading slashes rather than function as expected.

I see two ways to resolve this:

1. update the "Setup pages" action to reflect the correct `baseurl` which would be a breaking change, or
2. change the starter workflow, doing one or both of the following
   - Add a note that `--baseurl …` needs to be left out for a main site, or
   - Remove the `--baseurl` from the example altogether, make another workflow for subprojects specifically

I probably missed a cleaner solution, but this would at least work.

**Comment by Phantsure** [comment] 2022-08-16 13:13
@yoannchaudet Can you provide help here?

**Comment by bertptrs** [comment] 2022-08-17 11:09
@yoannchaudet thank you for looking into this!

It's not in my configuration file, but to support multiple deployment environments (e.g. `example.com`, `example.org/test`) it's useful to write URLs in your source code like

```html
<!DOCTYPE HTML>
<html>
<head>
    <link rel="stylesheet" href="{{ site.baseurl }}/assets/style.css">
</head>
</html>
```

This assumes (as do similar examples elsewhere) that `baseurl` does _not_ end in a slash, as the docs state. However, this is not how `baseurl` is set from the sample workflows, as mentioned above.

**Comment by JamesMGreene** [comment] 2022-08-18 23:45
FWIW, I believe the recommended approach to this is to use [Jekyll's `relative_url` and `absolute_url` Liquid filters](https://jekyllrb.com/docs/liquid/filters/), which will handle potentially doubled-up slashes (since Jekyll `v3.5.0`) for you.

e.g.

```html
<!DOCTYPE HTML>
<html>
<head>
    <link rel="stylesheet" href="{{ '/assets/style.css' | relative_url }}">
</head>
</html>
```

That said, I do think that removing the trailing slash from the `base_url` and `base_path` values is a practical improvement, so I'm pursuing the first steps toward that in our `actions/configure-pages` Action:
- https://github.com/actions/configure-pages/pull/19

After that gets released, I will follow-up here and update the Pages starter workflows as needed as well. 👍🏻

**Comment by JamesMGreene** [comment] 2022-08-19 14:34
@bertptrs If you'd be up for it, would love you to test out your workflow using the new `v2.0.0` release of `actions/configure-pages` and let us know if it resolves the issue! 🙏🏻 

```yaml
 - name: Setup Pages
   id: pages
   uses: actions/configure-pages@v2 # <-- updated version
 - run: bundle exec jekyll build --baseurl ${{ steps.pages.outputs.base_path }}
```

**Comment by bertptrs** [comment] 2022-08-24 15:44
I have updated my site to use `actions/configure-pges@v2` and it isn't broken, so that seems to work, thanks!

Now I should really update to use `relative_url` and `absolute_url` instead, but that doesn't work (yet) for my setup.

**Comment by JamesMGreene** [comment] 2022-08-25 17:31
@bertptrs Awesome, thanks for verifying on your end! 💖 

I'll do a bit more regression testing on our side, but I would expect to get those changes to the starter workflow merged yet this week. 👍🏻

**Closed** 2022-08-26 04:33 UTC
