### ISSUE TITLE
Did not find expected key [GITHUB_TOKEN]

### ISSUE THREAD

**Issue by princebansal** [actions/starter-workflows#146] opened 2019-09-26 06:30 UTC
Hey.
I added the `greetings.yaml` starter workflow in my repository. The workflow looks like this:
```name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
        pr-message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
```

But everytime it runs, it throws error: 
```
yaml: line 11: did not find expected key
```

I assume it is not able to find `GITHUB_TOKEN`. I read this [here](https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret): 

> The GITHUB_TOKEN secret is a GitHub App installation token scoped to the repository that contains your workflow. GitHub creates the GITHUB_TOKEN secret for you by default, but you must include it in your workflow file in order for actions to use it. You can use the GITHUB_TOKEN secret to make authenticated GitHub API calls on behalf of an action.

Please help on this

**Comment by peaceiris** [comment] 2019-09-26 06:35
https://github.com/actions/first-interaction/issues/8

**Comment by andymckay** [comment] 2019-10-07 21:50
Thanks @princebansal I think this is a duplicate of the issue that @peaceiris mentioned, so I'm going to close as being a duplicate of that issue. If that's not the case, my apologies. Since there's a dedicated repository for that project, if you could open issues on that repository it would be appreciated.

**Closed by andymckay** 2019-10-07 21:50 UTC
